run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - errcheck
    - gofumpt
    - gofmt
    - goimports
    - staticcheck
    - revive
issues:
  exclude-rules:
    - path: _test\.go
      text: 'should have comment'
